/* Generated from log.jsonl by shared/mklog.sh — do not edit by hand.
 * Exists only so the page still shows its timeline when opened over file://,
 * where fetch() of a sibling file is blocked. log.jsonl stays the source of truth. */
window.__POEM_LOG__ = [
{"round": 1, "title": "走进洞庭：天、水、北渚、白薠、木叶", "changed": "第一份可以走进去的洞庭：天/水/北渚/白薠/木叶/九嶷剪影，WASD + 触控漫游，右栏时间线读 log.jsonl", "why": "先做到能走进去：有地、有天、有相机、有字幕，右栏能读 log.jsonl。", "critic": "接近了 —— 秋风木叶、洞庭空波与白薠远望的空茫等待感对了，但六张几乎同一片湖天，缺少《湘夫人》独有的辨识物。", "gap": "在水中央建起那座荷盖香草之屋，让至少一个机位正对它而她始终不来。", "version": "versions/1/index.html", "shots": ["shots/1/1-beizhu.png", "shots/1/2-dongtingbo.png", "shots/1/3-muyexia.png", "shots/1/4-jiuyi.png", "shots/1/5-chengwang.png", "shots/1/6-dengdai.png"]},
{"round": 2, "title": "筑室兮水中，葺之兮荷盖", "changed": "筑室兮水中：木桩上的紫坛、一根根荪壁、桂栋兰橑、荷叶压成的屋顶、辛夷楣与白玉镇，四周三百片浮在波上的荷叶；顺手把九嶷从东边挪回南边", "why": "critic 说六张几乎同一片湖天，缺少《湘夫人》独有的辨识物。", "critic": "接近了 —— 秋风木叶、白薠、水中荷屋、九嶷剪影都在，氛围克制耐看，但可辨识度多半靠字幕，等待的「错位与不安」几乎缺席。", "gap": "加上罾挂树上、鸟萃蘋中、麋入庭中这组错位实体，让画面自己说「不对劲」。", "version": "versions/2/index.html", "shots": ["shots/2/1-beizhu.png", "shots/2/2-dongtingbo.png", "shots/2/3-muyexia.png", "shots/2/4-jiuyi.png", "shots/2/5-chengwang.png", "shots/2/6-dengdai.png"]},
{"round": 3, "title": "罾在木上，鸟在蘋中，麋在庭中，蛟在水裔", "changed": "错位：江皋上七株空树，三张罾挂在树上；五处蘋中落着鸟；麋走进为她盖的屋子在门前低头吃草；蛟的背脊在水裔上拱起两处", "why": "critic 说可辨识度多半靠字幕，等待的「错位与不安」几乎缺席。", "critic": "接近了 —— 白薠、罾挂木上、水中荷屋、九嶷与落叶都在，秋暮与空无也对，但第 3、6 机位偏空景，「等待落空」尚未压过风景。", "gap": "加一件顺流漂远的衣袖（捐余袂），让每个机位都能看见它慢慢漂走。", "version": "versions/3/index.html", "shots": ["shots/3/1-beizhu.png", "shots/3/2-dongtingbo.png", "shots/3/3-muyexia.png", "shots/3/4-jiuyi.png", "shots/3/5-chengwang.png", "shots/3/6-dengdai.png"]},
{"round": 4, "title": "捐余袂兮江中：素绢开始漂走", "changed": "三件顺流漂走的袖子和一件搁浅在澧浦的褋；绢贴着浪起伏、自己还在抖，是这个世界里唯一还在走而且再也不回来的东西", "why": "critic 说第 3、6 机位偏空景，「等待落空」尚未压过风景。", "critic": "接近了 —— 白薠、罾挂树、水中荷屋、九嶷诸象皆在，气息对；但两张近乎空景，仍偏「好看」多于「等不到」。", "gap": "在水面加一件顺流漂走的白色衣袖，六机位中至少两处可见。", "version": "versions/4/index.html", "shots": ["shots/4/1-beizhu.png", "shots/4/2-dongtingbo.png", "shots/4/3-muyexia.png", "shots/4/4-jiuyi.png", "shots/4/5-chengwang.png", "shots/4/6-dengdai.png"]}
];
