/* Generated from log.jsonl by shared/mklog.sh — do not edit by hand.
 * Exists only so the page still shows its timeline when opened over file://,
 * where fetch() of a sibling file is blocked. log.jsonl stays the source of truth. */
window.__POEM_LOG__ = [
{"round": 1, "title": "走进洞庭：天、水、北渚、白薠、木叶", "changed": "第一份可以走进去的洞庭：天/水/北渚/白薠/木叶/九嶷剪影，WASD + 触控漫游，右栏时间线读 log.jsonl", "why": "先做到能走进去：有地、有天、有相机、有字幕，右栏能读 log.jsonl。", "critic": "接近了 —— 秋风木叶、洞庭空波与白薠远望的空茫等待感对了，但六张几乎同一片湖天，缺少《湘夫人》独有的辨识物。", "gap": "在水中央建起那座荷盖香草之屋，让至少一个机位正对它而她始终不来。", "version": "versions/1/index.html", "shots": ["shots/1/1-beizhu.png", "shots/1/2-dongtingbo.png", "shots/1/3-muyexia.png", "shots/1/4-jiuyi.png", "shots/1/5-chengwang.png", "shots/1/6-dengdai.png"]},
{"round": 2, "title": "筑室兮水中，葺之兮荷盖", "changed": "筑室兮水中：木桩上的紫坛、一根根荪壁、桂栋兰橑、荷叶压成的屋顶、辛夷楣与白玉镇，四周三百片浮在波上的荷叶；顺手把九嶷从东边挪回南边", "why": "critic 说六张几乎同一片湖天，缺少《湘夫人》独有的辨识物。", "critic": "接近了 —— 秋风木叶、白薠、水中荷屋、九嶷剪影都在，氛围克制耐看，但可辨识度多半靠字幕，等待的「错位与不安」几乎缺席。", "gap": "加上罾挂树上、鸟萃蘋中、麋入庭中这组错位实体，让画面自己说「不对劲」。", "version": "versions/2/index.html", "shots": ["shots/2/1-beizhu.png", "shots/2/2-dongtingbo.png", "shots/2/3-muyexia.png", "shots/2/4-jiuyi.png", "shots/2/5-chengwang.png", "shots/2/6-dengdai.png"]},
{"round": 3, "title": "罾在木上，鸟在蘋中，麋在庭中，蛟在水裔", "changed": "错位：江皋上七株空树，三张罾挂在树上；五处蘋中落着鸟；麋走进为她盖的屋子在门前低头吃草；蛟的背脊在水裔上拱起两处", "why": "critic 说可辨识度多半靠字幕，等待的「错位与不安」几乎缺席。", "critic": "接近了 —— 白薠、罾挂木上、水中荷屋、九嶷与落叶都在，秋暮与空无也对，但第 3、6 机位偏空景，「等待落空」尚未压过风景。", "gap": "加一件顺流漂远的衣袖（捐余袂），让每个机位都能看见它慢慢漂走。", "version": "versions/3/index.html", "shots": ["shots/3/1-beizhu.png", "shots/3/2-dongtingbo.png", "shots/3/3-muyexia.png", "shots/3/4-jiuyi.png", "shots/3/5-chengwang.png", "shots/3/6-dengdai.png"]},
{"round": 4, "title": "捐余袂兮江中：素绢开始漂走", "changed": "三件顺流漂走的袖子和一件搁浅在澧浦的褋；绢贴着浪起伏、自己还在抖，是这个世界里唯一还在走而且再也不回来的东西", "why": "critic 说第 3、6 机位偏空景，「等待落空」尚未压过风景。", "critic": "接近了 —— 白薠、罾挂树、水中荷屋、九嶷诸象皆在，气息对；但两张近乎空景，仍偏「好看」多于「等不到」。", "gap": "在水面加一件顺流漂走的白色衣袖，六机位中至少两处可见。", "version": "versions/4/index.html", "shots": ["shots/4/1-beizhu.png", "shots/4/2-dongtingbo.png", "shots/4/3-muyexia.png", "shots/4/4-jiuyi.png", "shots/4/5-chengwang.png", "shots/4/6-dengdai.png"]},
{"round": 5, "title": "让那件袂真的进画：三个定机位都看得见它", "changed": "把四件素绢挪进三个定机位的取景里并放大提亮；截图改成固定三帧、固定时刻、可复现，并且不再显示字幕——critic 从这一轮起只看画面", "why": "critic 连着两轮点同一个缺口：袂在世界里，但一张截图里都看不见。", "critic": "接近了（7/10）—— 秋风木叶、水中荷屋与九嶷群峰已相当到位，但最具辨识度的「罾在木上、鸟萃蘋中」错位完全没入画。", "gap": "把渔网明确挂到近景枯树枝上，并让它进入至少一个固定机位的画面中心。", "score": 7, "version": "versions/5/index.html", "noticed": "机位从 6 个减到 3 个（本机负载），截图改一次性、有墙钟硬超时、拍完即退。", "shots": ["shots/5/1-beizhu.png", "shots/5/5-chengwang.png", "shots/5/6-dengdai.png"]},
{"round": 6, "title": "罾何为兮木上：把网挂进画面中心", "changed": "为三个定机位各立一株近景枯树（有一株站在水里），把罾挂上去；网改成真的会垂、会收口、会扭的软网；蘋中的鸟也补进等待机位", "why": "critic：最具辨识度的「罾在木上、鸟萃蘋中」错位完全没入画。", "critic": "接近了（7/10）—— 白薠、落叶、水中荷屋、九嶷剪影、木上之罾都在，秋水空阔可辨；但更像一幅好看的荒景，缺人的等待痕迹。", "gap": "在等待机位前加一片顺流漂走的白色衣袖，长久不沉。", "score": 7, "version": "versions/6/index.html", "shots": ["shots/6/1-beizhu.png", "shots/6/5-chengwang.png", "shots/6/6-dengdai.png"]},
{"round": 7, "title": "袂要看得出是衣料：一头宽、一头收口、半沉在水里", "changed": "在「时不可兮骤得」那个机位跟前放一件近而大的袂；绢改成一头宽一头收口、边缘软、中间有褶；颜色压成暮色里湿透的灰白，不再是发光的纸", "why": "critic：更像一幅好看的荒景，缺人的等待痕迹。", "critic": "接近了（7/10）—— 秋水白薠、木叶不尽、树上挂罾、水中荷屋与远山九嶷都在，空无一人的等待感成立，但画面仍偏「好看的黄昏风景」。", "gap": "让木叶落点与水面激起涟漪、并加入蘋中栖鸟，把静态美景变成持续流逝的计时器。", "score": 7, "version": "versions/7/index.html", "shots": ["shots/7/1-beizhu.png", "shots/7/5-chengwang.png", "shots/7/6-dengdai.png"]},
{"round": 8, "title": "观流水兮潺湲：让水替落叶记时间", "changed": "每一片落到水上的木叶都荡开一圈，圈慢慢大、慢慢淡；蘋中的鸟放大到看得见，并补进两个机位的前景", "why": "critic：更像一幅好看的黄昏风景，需要把静态美景变成持续流逝的计时器。", "critic": "接近了（7/10）—— 木上之罾、水中荷屋与九嶷群峰都认得出，但满屏白薠更像秋景，「等不到」的证据太少。", "gap": "在主机位水面放一件正漂走的衣袖，让空等留下可见痕迹。", "score": 7, "version": "versions/8/index.html", "shots": ["shots/8/1-beizhu.png", "shots/8/5-chengwang.png", "shots/8/6-dengdai.png"]},
{"round": 9, "title": "踩出来的那条路：等待留下的唯一痕迹", "changed": "白薠里踩出一条从高处通到水边的路，草被踏平、踏短——来回走了很多趟；顺着这条路补了一件正漂过眼前的袂", "why": "critic：满屏白薠更像秋景，等不到的证据太少。", "critic": "接近了（7/10）—— 白薠、落叶、罾挂木上、水中荷屋与九嶷都在，认得出楚辞秋水，但「等而不得」的人味不足。", "gap": "让那只被弃的衣袂在三个机位都可见地顺流漂过，作画面里唯一的人迹。", "score": 7, "version": "versions/9/index.html", "shots": ["shots/9/1-beizhu.png", "shots/9/5-chengwang.png", "shots/9/6-dengdai.png"]},
{"round": 10, "title": "捐余袂兮江中：挂在枯枝上的那件衣裳", "changed": "两件被丢下的衣裳挂到枯枝上（和罾缠在同一株死树里），一件皱着丢在骋望的脚边；顺手修掉贴着镜头的那片叶子——它会被近裁剪面切开，糊住四分之一画面", "why": "critic：让那只被弃的衣袂在三个机位都可见地顺流漂过，作画面里唯一的人迹。", "critic": "接近了（7/10）—— 白薠、落叶、水中荷屋与九嶷剪影已成立，罾挂树上尤准，但落日太好看，等待之苦被风景压住。", "gap": "在水中屋前加一处已铺好却空着的席案（夕张），让「她未至」被看见。", "score": 7, "version": "versions/10/index.html", "noticed": "critic 还看见了那片糊住画面的近景叶子，这一轮一起修了。下一个循环该做的是「夕张」：把席案铺好，空着。", "shots": ["shots/10/1-beizhu.png", "shots/10/5-chengwang.png", "shots/10/6-dengdai.png"], "stop": true, "stop_reason": "跑满 10 轮（10 轮 / critic 连两轮「我们赢」 / STOP / 周限不足 1 小时，先到先停）"},
{"round": 11, "at": "2026-09-17T00:45Z", "title": "机制改标：这一首改用纯 Ralph", "changed": "加了 PRD.md（目标 + 意象对照表 + 人迹的规矩 + 待办清单）和 progress.txt；POLISH.md 改写成 Ralph 的固定 prompt；页脚 loop 标注从「Gauntlet 独立 critic + Ralph 一轮一事」改成「Ralph（PRD + progress，一轮一事）」；截图脚本换成 chrome-headless-shell 一次性进程（nice -n 15、90 秒 alarm、--virtual-time-budget=5000、load<6 且空闲>40% 才开工）", "why": "船长裁定：一首只用一种循环机制，混合的效果不好；白天他在用这台电脑，渲染必须更轻。", "critic": "自检：三机位重拍通过，一轮 5.7 秒（换脚本前是分钟级）；画面无变化，人形零；下一条待办是衣裳重做。", "gap": "三个机位里唯一的人迹——那几件被捐的衣裳——现在读起来是一块灰蓝色的硬板，不像布。", "score": 7, "shots": ["shots/11/1-beizhu.png", "shots/11/5-chengwang.png", "shots/11/6-dengdai.png"], "version": "versions/11/index.html"}
];
